version: '3.7'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: kramsayu/lab4-ex:compose-django
    container_name: compose-django 
    ports:
      - 8000:8000
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    image: kramsayu/lab4-ex:compose-monitoring
    container_name: monitoring 
    network_mode: "host"
